[package]
name = "pyrevm"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
revm = "7.1.0"
revm-interpreter = "3.3.0"
tracing = "0.1"
pyo3 = { version = "0.19", features = ["extension-module"] }
ruint = { version = "1.10", features = ["pyo3"] }
